Update epam_training_progect_pipe_3

diff --git a/jenkinsfiles/epam_training_progect_pipe_3 b/jenkinsfiles/epam_training_progect_pipe_3
--- a/jenkinsfiles/epam_training_progect_pipe_3
+++ b/jenkinsfiles/epam_training_progect_pipe_3
@@ -1,36 +1,60 @@
-stage('Build') {
-  // The first milestone step starts tracking concurrent build order
-  milestone()
-  node {
-    echo "Building"
-  }
-}
+#!groovy
 
-// This locked resource contains both Test stages as a single concurrency Unit.
-// Only 1 concurrent build is allowed to utilize the test resources at a time.
-// Newer builds are pulled off the queue first. When a build reaches the
-// milestone at the end of the lock, all jobs started prior to the current
-// build that are still waiting for the lock will be aborted
+properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '10', numToKeepStr: '5')), disableConcurrentBuilds()])
+
+
+node('Backend'){
+
 lock(resource: 'myResource', inversePrecedence: true){
-  node('Backend') {
-    stage('Unit Tests') {
-      echo "Unit Tests"
+    
+    
+    if ( ref == 'refs/heads/backend' )  {
+        stage('Checkout')  {            
+            git branch: 'backend', credentialsId: 'ssh-key-main', url: 'git@github.com:Ihor-Porokhnia/WebApp.git'
+        }
+        
+        
+        
+        stage('Build') {
+            try { 
+            sh 'mvn versions:set  -DnewVersion=0.0.' + env.BUILD_ID +'-SNAPSHOT'
+            telegramSend(message: 'Build # ' + env.BUILD_ID + ' successfully done' , chatId: -393518449)
+            sh 'mvn clean install'
+            
+        }
+        catch (exc) {
+            telegramSend(message: 'Build # ' + env.BUILD_ID + ' successfully failed' , chatId: -393518449)
+            error 'FAIL'
+        }
+        }
+        stage('Deploy')  {
+           try {
+               sh 'sudo cp target/Backend-0.0.'+ env.BUILD_ID + '-SNAPSHOT.war /opt/tomcat/latest/webapps/Backend.war'
+               sh 'sudo systemctl restart tomcat'
+               sh 'sudo systemctl restart nginx'
+               telegramSend(message: 'Staging deploy build # ' + env.BUILD_ID + ' successfully done' , chatId: -393518449)
+           }
+            catch (exc) {
+            telegramSend(message: 'Staging deploy build # ' + env.BUILD_ID + ' successfully failed' , chatId: -393518449)
+            error 'FAIL'
+            
+        }
+        }
+             
+    } else {
+              sh 'echo notback'
     }
-    stage('System Tests') {
-      echo "System Tests"
-    }
-  }
-  milestone()
+}
 }
 
-// The Deploy stage does not limit concurrency but requires manual input
-// from a user. Several builds might reach this step waiting for input.
-// When a user promotes a specific build all preceding builds are aborted,
-// ensuring that the latest code is always deployed.
-stage('Deploy') {
-  input "Deploy?"
-  milestone()
-  node {
-    echo "Deploying"
-  }
+node('Frontend'){
+    if ( ref == 'refs/heads/frontend')  {
+              sh 'echo $ref'
+    } else {
+              sh 'echo notfront'
+              sh 'uptime'
+              lock(resource: 'myResource', inversePrecedence: true){
+              }
+              sh 'uptime'
+    }
 }
